// <auto-generated />
using System;
using IMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420194617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("IMS.Domain.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryID = 1,
                            InventoryName = "Bike Seat",
                            Price = 2.0,
                            Quantity = 10
                        },
                        new
                        {
                            InventoryID = 2,
                            InventoryName = "Bike Body",
                            Price = 4.0,
                            Quantity = 20
                        },
                        new
                        {
                            InventoryID = 3,
                            InventoryName = "Bike Wheel",
                            Price = 6.0,
                            Quantity = 30
                        },
                        new
                        {
                            InventoryID = 4,
                            InventoryName = "Bike Pedal",
                            Price = 8.0,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("IMS.Domain.InventoryTransaction", b =>
                {
                    b.Property<int>("InventoryTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryTransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("InventoryTransactionID");

                    b.HasIndex("InventoryID");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("IMS.Domain.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Price = 200.0,
                            ProductName = "Bike",
                            Quantity = 10
                        },
                        new
                        {
                            ProductID = 2,
                            Price = 400.0,
                            ProductName = "Car",
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("IMS.Domain.ProductInventory", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID", "InventoryID");

                    b.HasIndex("InventoryID");

                    b.ToTable("ProductInventories");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            InventoryID = 1,
                            InventoryQuantity = 10
                        },
                        new
                        {
                            ProductID = 1,
                            InventoryID = 2,
                            InventoryQuantity = 20
                        },
                        new
                        {
                            ProductID = 1,
                            InventoryID = 3,
                            InventoryQuantity = 20
                        },
                        new
                        {
                            ProductID = 1,
                            InventoryID = 4,
                            InventoryQuantity = 20
                        });
                });

            modelBuilder.Entity("IMS.Domain.ProductTransaction", b =>
                {
                    b.Property<int>("ProductTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SONumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductTransactionID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductTransactions");
                });

            modelBuilder.Entity("IMS.Domain.InventoryTransaction", b =>
                {
                    b.HasOne("IMS.Domain.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("IMS.Domain.ProductInventory", b =>
                {
                    b.HasOne("IMS.Domain.Inventory", "Inventory")
                        .WithMany("ProductInventories")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.Domain.Product", "Product")
                        .WithMany("ProductInventories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.Domain.ProductTransaction", b =>
                {
                    b.HasOne("IMS.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.Domain.Inventory", b =>
                {
                    b.Navigation("ProductInventories");
                });

            modelBuilder.Entity("IMS.Domain.Product", b =>
                {
                    b.Navigation("ProductInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
